# permissions for end users to view books.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: book-viewer-role
rules:
- apiGroups:
  - webapp.ydzs.io
  resources:
  - books
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.ydzs.io
  resources:
  - books/status
  verbs:
  - get
